server.port=8888

spring.ai.model.chat=openai
spring.ai.model.image=openai
spring.ai.openai.chat.options=gpt-4o
spring.ai.openai.chat.options.temperature=1.0
spring.ai.openai.image.options.model=dall-e-3
spring.ai.openai.image.options.size=1024x1024
spring.ai.openai.image.options.style=natural
spring.ai.openai.api-key=${OPENAI_API_KEY}

gg.jte.usePrecompiledTemplates=false
gg.jte.developmentMode=true